services:
  r8-vimkim-service:
    build: ./r8-cubrid/.
    hostname: iuser8btw-1
    privileged: true
    tty: true
    stdin_open: true
    environment:
      - USERNAME=vimkim-r8
      - USER_PASSWORD=password
      - container=docker
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - vimkim-r8-home-1:/home/vimkim-r8
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      vimkim_net:
        ipv4_address: 192.168.4.108

networks:
  vimkim_net:
    name: vimkim_net
    external: true

volumes:
  vimkim-r8-home-1:
