version: '3.9'
services:
  vk-arch-service-1:
    build: .
    container_name: vk-arch-container-1
    hostname: iusearchbtw
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - vk-arch-home-1:/home/vimkim
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      dev-net:
      ipv4_address: 192.168.4.2

networks:
  vimkim-net:
    name: dev-net
    external: true

volumes:
  vk-arch-home-1:


