services:
  vk-fedora-service-1:
    build: .
    container_name: vk-fedora-container-1
    hostname: iusefedorabtw
    volumes:
      - ./workspace:/home/vimkim/workspace
      - vk-fedora-home-1:/home/vimkim
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    privileged: true
    networks:
      dev-net:
        ipv4_address: 192.168.2.120
  vk-fedora-service-2:
    build: .
    container_name: vk-fedora-container-2
    hostname: iusefedorabtw
    volumes:
      - vk-fedora-home-2:/home/vimkim
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    privileged: true
    networks:
      dev-net:
        ipv4_address: 192.168.2.121

networks:
  dev-net:
    name: dev-net
    external: true

volumes:
  vk-fedora-home-1:
  vk-fedora-home-2:
